# Generated by Django 4.2 on 2023-04-19 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="manufacturer",
            old_name="address",
            new_name="country",
        ),
        migrations.RemoveField(
            model_name="manufacturer",
            name="phone_number",
        ),
    ]
